---

- name: 'update timezone'
  timezone:
    name: "{{ timezone_config }}"
  register: __timezone_update

- name: 'restart cron if needed'  # noqa 503
  service:
    name: "{{ _timezone_cron_service_name }}"
    state: 'restarted'
  when: >
    timezone_restart_cron
    and __timezone_update.changed
