---

- hosts: all
  name: 'Converge'
  become: True

  tasks:
    - import_role:
        name: 'ansible-role-timezone'
      vars:
        timezone_config: 'Europe/Paris'
        timezone_restart_cron: False
